const dashboardRouteNames = {
  HOME: 'HOME',

  //Shop
  SHOP: 'SHOP',
  CART: 'CART',
  CHECKOUT: 'CHECKOUT',
  PRODUCT_DETAILS: 'PRODUCT_DETAILS',

  // Logs
  LOGS: 'LOGS',
  LOGS_PREFERENCES: 'LOGS_PREFERENCES',
  ADD_WEIGHT_LOG: 'ADD_WEIGHT_LOG',
  ADD_WORKOUT_LOG: 'ADD_WORKOUT_LOG',
  ADD_MEAL_LOG: 'ADD_MEAL_LOG',
  ADD_SUPPLEMENTS_LOG: 'ADD_SUPPLEMENTS_LOG',
  ADD_ALCOHOL_INTAKE_LOG: 'ADD_ALCOHOL_INTAKE_LOG',
  ADD_WATER_LOG: 'ADD_WATER_LOG',

  // Consultation
  CONSULTATION: 'CONSULTATION',
  CONSULTATION_BOOKING_CHAT: 'CONSULTATION_BOOKING_CHAT',
  CONSULTATION_BOOKING_SUCCESS: 'CONSULTATION_BOOKING_SUCCESS',
  CONSULTATION_BOOK: 'CONSULATION_BOOK',

  // Profile
  USER_PROFILE: 'USER_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  SETTINGS: 'SETTINGS',

  // Billing & Invoices
  INVOICES: 'INVOICES',

  // Reminders
  REMINDERS: 'REMINDERS',

  // Devices
  FITNESS_DEVICES: 'FITNESS_DEVICES',

  // Scores
  SCORES: 'SCORES',
  LIFESTYLE_ASSESSMENT_QUESTION: 'LIFESTYLE_ASSESSMENT_QUESTION',

  // Workout Activity & Nutrition
  NUTRITION_ANALYSIS: 'NUTRITION_ANALYSIS',
  WORKOUT_PLAN: 'WORKOUT_PLAN',
  TODAYS_WORKOUT: 'TODAYS_WORKOUT',
  TODAYS_WORKOUT_TIMER: 'TODAYS_WORKOUT_TIMER',
  HEART_RATE: 'YOUR_HEART_RATE',
};

export default dashboardRouteNames;
