const onboardingRouteNames = {
  // Information & Permissions
  BASIC_INFORMATION: "ONBOARDING_BASIC_INFORMATION",
  BMI: "ONBOARDING_BMI",
  ADDRESS: "ONBOARDING_ADDRESS",
  PERMISSIONS: "ONBOARDING_PERMISSIONS",
  DEVICES: "ONBOARDING_DEVICES",
  GOALS: "ONBOARDING_GOALS",

  // Subscription
  CHOOSE_PLAN: "ONBOARDING_CHOOSE_PLAN",
  BILLING_AND_ADDONS: "ONBOARDING_BILLING_AND_ADDONS",

  // Booking
  BOOK_TEST: "BOOK_TEST",
  BOOK_TEST_INFORMATION: "BOOK_TEST_INFORMATION",
  BOOK_TEST_SUCCESS: "BOOK_TEST_SUCCESS",
};

export default onboardingRouteNames;
