const workoutRouteNames = {
  EXERCISE_AND_NUTRITION_PLAN: 'EXERCISE_AND_NUTRITION_PLAN',
  EXERCISE_PROGRESS: 'EXERCISE_PROGRESS',
  EXERCISE_TIMELINE_OVERVIEW: 'EXERCISE_TIMELINE_OVERVIEW',
};

export default workoutRouteNames;
