import {Dimensions, StatusBar, StyleSheet} from 'react-native';
import {COLORS} from '../../constants/colors';
import {FONT_FAMILY} from '../../constants/font-family';

const {height, width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.TRANSPARENT_BLACK,
    // padding: 10,
  },
  headerContainer: {
    paddingTop: StatusBar.currentHeight + 25,
    paddingVertical: 25,
    paddingHorizontal: 20,
    //  flexDirection: 'row',
    //backgroundColor: 'red',
    // alignItems: 'center',
  },

  tabsContainer: {
    padding: 12.5,
    borderWidth: 0.5,
    borderColor: COLORS.GREY,
    // marginHorizontal: 20,
    borderTopRightRadius: 5,
    backgroundColor: COLORS.TRANSPARENT_BLACK,
    overflow: 'hidden',
    marginBottom: 40,
    flex: 1,
    borderBottomRightRadius: 5,
    borderLeftWidth: 0,
  },
  infoContainer: {
    padding: 12.5,
    borderWidth: 0.5,
    borderColor: COLORS.GREY,
    marginHorizontal: 20,
    borderRadius: 5,
    backgroundColor: COLORS.TRANSPARENT_BLACK,
    overflow: 'hidden',
    marginBottom: 40,
    flex: 3.25,
  },

  absolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },

  headerTitle: {
    fontFamily: FONT_FAMILY.primaryMedium,
    color: COLORS.PRIMARY,
    fontSize: 20,
  },
  list: {
    flexDirection: 'row',
    //backgroundColor: 'red',
    marginVertical: 1.5,
  },

  heading: {
    fontFamily: FONT_FAMILY.primaryMedium,
    color: COLORS.PRIMARY,
    fontSize: 13,
    marginBottom: 5,
  },
  subHeading: {
    fontFamily: FONT_FAMILY.primaryMedium,
    color: COLORS.WHITE,
    fontSize: 13,
  },
  value: {
    fontFamily: FONT_FAMILY.primary,
    color: COLORS.WHITE,
    fontSize: 11,
    flex: 1,
  },
  bullet: {
    height: 3,
    width: 3,
    backgroundColor: COLORS.WHITE,
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    marginTop: 5.5,
    marginLeft: 15,
  },
  backContainer: {
    height: 30,
    width: 30,
    backgroundColor: COLORS.TRANSPARENT_WHITE,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },

  circle: {
    height: 60,
    width: 60,
    backgroundColor: COLORS.TRANSPARENT_WHITE,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
  },
  label: {
    fontFamily: FONT_FAMILY.primarySemiBold,
    color: COLORS.WHITE,
    fontSize: 10,
    marginBottom: 20,
    textAlign: 'center',
  },
  smallBtn: {
    flex: 1,
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 30,
    // paddingHorizontal: 10,
    paddingVertical: 3.5,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY,
    alignItems: 'center',
    marginHorizontal: 5,
    justifyContent: 'center',
  },
  smallBtnTxt: {
    fontFamily: FONT_FAMILY.primary,
    color: COLORS.BLACK,
    fontSize: 9,
  },
  smallBorderBtn: {
    flex: 1,
    // backgroundColor: COLORS.PRIMARY,
    borderRadius: 30,
    // paddingHorizontal: 10,
    paddingVertical: 3.5,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.WHITE,
    alignItems: 'center',
    marginHorizontal: 5,
    justifyContent: 'center',
  },
  smallBorderBtnTxt: {
    fontFamily: FONT_FAMILY.primary,
    color: COLORS.WHITE,
    fontSize: 9,
  },

  btn: {
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 30,
    // paddingHorizontal: 10,
    paddingVertical: 12,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY,
    alignItems: 'center',
    marginHorizontal: 5,
    justifyContent: 'center',
    marginHorizontal: 20,
  },
  btnTxt: {
    fontFamily: FONT_FAMILY.primaryMedium,
    color: COLORS.BLACK,
    fontSize: 12,
  },
  borderBtn: {
    // backgroundColor: COLORS.PRIMARY,
    borderRadius: 30,
    // paddingHorizontal: 10,
    paddingVertical: 12,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: COLORS.WHITE,
    alignItems: 'center',
    marginHorizontal: 5,
    justifyContent: 'center',
    marginHorizontal: 20,
  },
  borderBtnTxt: {
    fontFamily: FONT_FAMILY.primaryMedium,
    color: COLORS.WHITE,
    fontSize: 12,
  },
  nearby: {
    fontFamily: FONT_FAMILY.primaryMedium,
    color: COLORS.SECONDARY,
    fontSize: 11,
    textAlign: 'center',
    // flex: 1,
    marginTop: 10,
    textDecorationLine: 'underline',
  },

  or: {
    fontFamily: FONT_FAMILY.primaryMedium,
    color: COLORS.WHITE,
    fontSize: 11,
    textAlign: 'center',
    // flex: 1,
    marginTop: 10,
    //textDecorationLine: 'underline',
  },

  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
});
